name: Publish Docker Image

on:
  schedule:
    - cron:  '0 0 * * 0'
  push:
    branches:
      - master
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/docker/cli@master
      with:
        args: "build -t glances-docker ."
    - uses: actions/docker/tag@master
      with:
        args: "glances-docker sbonnick/glances-docker"
    - uses: actions/docker/login@master
      with:
        secrets: ["DOCKER_USERNAME", "DOCKER_PASSWORD"]
    - uses: actions/docker/cli@master
      with:
        args: "push sbonnick/glances-docker"
    
