name: Publish Docker Image

on:
  schedule:
    - cron:  '0 0 * * 0'
  push:
    branches:
      - master
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: "actions/docker/cli@master"
      args: "build -t sbonnick/glances-docker ."
    - uses: "actions/docker/tag@master"
      args: "glances-docker sbonnick/glances-docker"
    - uses: actions/docker/login@master
      secrets: ["DOCKER_USERNAME", "DOCKER_PASSWORD"]
    
